name: Android CI (Build APK)

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configure Android SDK (use preinstalled)
        run: |
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept Android licenses and ensure packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Bootstrap Gradle (no wrapper yet)
        run: |
          curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip -d $RUNNER_TEMP
          echo "GRADLE_HOME=$RUNNER_TEMP/gradle-8.7" >> $GITHUB_ENV
          echo "$RUNNER_TEMP/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Generate Gradle Wrapper
        run: |
          gradle -v
          gradle wrapper --gradle-version 8.7

      - name: Build debug APK
        run: |
          chmod +x ./gradlew || true
          ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Appmux-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk


